---
- name: Install Redis
  become: yes
  yum:
      name: redis
      update_cache: yes
      state: present
  when: redis_install and (ansible_pkg_mgr == "yum")

- name: Adust Redis Configuration
  become: yes
  lineinfile:
      dest: /etc/redis.conf
      regexp: '^bind 127.0.0.1'
      line: '#bind 127.0.0.1'
  when: redis_install

- name: Disable Transparent Huge Pages
  become: yes
  debug:
      msg: "TODO: https://access.redhat.com/solutions/46111"

- name: Enable Redis
  become: yes
  command: "systemctl enable redis"

- name: Start Redis
  become: yes
  command: "systemctl restart redis"

- name: Dump Redis Status
  become: yes
  command: "systemctl status redis"

- name: Test Redis
  become: no
  command: "redis-cli ping"
