---
- name: Copy Repository File
  become: yes
  template:
        src: templates/mongo-org.repo.j2
        dest: /etc/yum.repos.d/mongodb-org-3.4.repo
  when: mongodb_install and (ansible_pkg_mgr == "yum")

# currently, there is a gpg key mismatch so I'm turning off checking for now
- name: Install MongoDB
  become: yes
  yum:
      name: "mongodb-org"
      state: present
      update_cache: yes
      disable_gpg_check: yes
  when: mongodb_install and (ansible_pkg_mgr == "yum")

- name: Install MongoDB Configuration
  become: yes
  template:
      src: templates/mongod.conf.js
      dest: /etc/mongod.conf
      mode: 0444
      backup: yes
      force: yes
  when: mongodb_install

- name: Start MongoDB daemon
  become: yes
  service:
      name: mongod
      state: restarted
      enabled: yes
  when: mongodb_install
